package caldeiraVapor.mensagens;

public enum TipoDeMensagem {

	// Lista direto da especificacao
	// nao quer dizer que todas sejam usadas

	UNSPECIFIED_MESSAGE,

	// Mensagens do controle para a planta
	MODE,
	PROGRAM_READY,
	OPEN_VALVE,
        CLOSE_VALVE,
	OPEN_PUMP,
	CLOSE_PUMP,
	PUMP_FAILURE_DETECTION,
	PUMP_CONTROL_FAILURE_DETECTION,
	LEVEL_FAILURE_DETECTION,
	STEAM_FAILURE_DETECTION,
	PUMP_REPAIRED_ACKNOWLEDGEMENT,
	PUMP_CONTROL_REPAIRED_ACKNOWLEDGEMENT,
	LEVEL_REPAIRED_ACKNOWLEDGEMENT,
	STEAM_REPAIRED_ACKNOWLEDGEMENT,

	// Mensagens da planta para o controle
	STOP,
	STEAM_BOILER_WAITING,
	PHYSICAL_UNITS_READY,
	PUMP_STATE,
	PUMP_CONTROL_STATE,
	LEVEL,
	STEAM,
	PUMP_REPAIRED,
	PUMP_CONTROL_REPAIRED,
	LEVEL_REPAIRED,
	STEAM_REPAIRED,
	PUMP_FAILURE_ACKNOWLEDGEMENT,
	PUMP_CONTROL_FAILURE_ACKNOWLEDGEMENT,
	LEVEL_FAILURE_ACKNOWLEDGEMENT,
	STEAM_OUTCOME_FAILURE_ACKNOWLEDGEMENT;
}
